# Generated by Django 3.2.25 on 2025-12-12 00:27

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('matricula', models.CharField(db_index=True, help_text='Placa de matricula do veiculo', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Placa inválida. Ex: ABC-1234 ou ABC-123-XY', regex='^[A-Z]{2,3}-\\d{1,4}(-[A-Z]{1,2})?$')])),
                ('capacidade', models.PositiveIntegerField(help_text='Numero maximo de Passageiros', validators=[django.core.validators.MinValueValidator(1)])),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='core.motorista')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['matricula'],
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=255)),
                ('hora_partida', models.TimeField(default=datetime.time(5, 30))),
                ('hora_chegada', models.TimeField(default=datetime.time(7, 0))),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('alunos', models.ManyToManyField(related_name='rotas_transporte', to='core.Aluno')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotas', to='transporte.veiculo')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'ordering': ['nome'],
            },
        ),
    ]
