# Generated by Django 3.2.25 on 2025-11-24 02:54

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=30)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, help_text='Salário do usuário (se vazio, aplica valor padrão do cargo).', max_digits=10, null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('salario_padrao', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_motoristas/')),
                ('data_nascimento', models.DateField()),
                ('nrBI', models.CharField(help_text='Numero de bilhere de identidade', max_length=30, unique=True)),
                ('carta_conducao', models.CharField(help_text='Numero da carta de conducao', max_length=30, unique=True)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='MZ')),
                ('endereco', models.TextField(blank=True, help_text='bairro, Quarterao, Numero da casa', null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to=models.Q(('role__nome', 'MOTORISTA')), on_delete=django.db.models.deletion.CASCADE, related_name='perfil_motorista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Encarregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_encarregados/')),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='MZ')),
                ('nrBI', models.CharField(help_text='introduza o numero de bilhere de identidade', max_length=30, unique=True)),
                ('endereco', models.TextField(blank=True, help_text='bairro, Q, N da casa', null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to=models.Q(('role__nome', 'ENCARREGADO')), on_delete=django.db.models.deletion.CASCADE, related_name='perfil_encarregado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_alunos/')),
                ('data_nascimento', models.DateField()),
                ('nrBI', models.CharField(help_text='introduza o numero de bilhere de identidade', max_length=30, unique=True)),
                ('escola_dest', models.CharField(max_length=255)),
                ('classe', models.CharField(max_length=25)),
                ('mensalidade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('encarregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='core.encarregado')),
                ('user', models.OneToOneField(limit_choices_to=models.Q(('role__nome', 'ALUNO')), on_delete=django.db.models.deletion.CASCADE, related_name='perfil_aluno', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.cargo'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
