# Generated by Django 3.2.25 on 2025-12-14 10:39

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Digite um email válido')])),
                ('nome', models.CharField(max_length=30)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Salário do usuário (se vazio, aplica valor padrão).', max_digits=10, null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='Os grupos aos quais este usuário pertence.', related_name='custom_user_groups', to='auth.Group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permissões específicas para este usuário.', related_name='custom_user_permissions', to='auth.Permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_motoristas/')),
                ('data_nascimento', models.DateField()),
                ('nrBI', models.CharField(db_index=True, help_text='Número de bilhete de identidade', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^\\d{9}[A-Z]{2}$', 'Formato inválido para BI')])),
                ('carta_conducao', models.CharField(db_index=True, help_text='Número da carta de condução', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{6,}$', 'Formato inválido para carta de condução')])),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='MZ')),
                ('endereco', models.TextField(blank=True, help_text='bairro, Quarteirão, Número da casa', null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to=models.Q(('role', 'MOTORISTA')), on_delete=django.db.models.deletion.CASCADE, related_name='perfil_motorista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Encarregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_encarregados/')),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='MZ')),
                ('nrBI', models.CharField(db_index=True, help_text='Número de bilhete de identidade', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^\\d{9}[A-Z]{2}$', 'Formato inválido para BI')])),
                ('endereco', models.TextField(blank=True, help_text='bairro, Q, N da casa', null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to=models.Q(('role', 'ENCARREGADO')), on_delete=django.db.models.deletion.CASCADE, related_name='perfil_encarregado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_alunos/')),
                ('data_nascimento', models.DateField()),
                ('nrBI', models.CharField(db_index=True, help_text='Número de bilhete de identidade', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^\\d{9}[A-Z]{2}$', 'Formato inválido para BI')])),
                ('escola_dest', models.CharField(db_index=True, max_length=255)),
                ('classe', models.CharField(max_length=25)),
                ('mensalidade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('encarregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='core.encarregado')),
                ('user', models.OneToOneField(limit_choices_to=models.Q(('role', 'ALUNO')), on_delete=django.db.models.deletion.CASCADE, related_name='perfil_aluno', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
