# Generated by Django 3.2.25 on 2025-12-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ALUNO', 'Aluno'), ('ENCARREGADO', 'Encarregado'), ('MOTORISTA', 'Motorista')], default='ADMIN', max_length=20),
        ),
    ]
