# Generated by Django 3.2.25 on 2026-01-08 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nrBI',
            field=models.CharField(db_index=True, help_text='Número de bilhete de identidade', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}[A-Z]{1}$', 'Formato inválido para BI')]),
        ),
        migrations.AlterField(
            model_name='encarregado',
            name='nrBI',
            field=models.CharField(db_index=True, help_text='Número de bilhete de identidade', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}[A-Z]{1}$', 'Formato inválido para BI')]),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='nrBI',
            field=models.CharField(db_index=True, help_text='Número de bilhete de identidade', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}[A-Z]{1}$', 'Formato inválido para BI')]),
        ),
    ]
